import {
  FaReact,
  FaNodeJs,
  FaPython,
  FaDocker,
  FaAws,
  FaHtml5,
  FaCss3Alt,
  FaJava,
  FaSwift,
  FaGithub,
  FaGitAlt,
  FaDatabase,
  FaFlask,
  FaProjectDiagram,
} from "react-icons/fa";
import {
  SiJavascript,
  SiTypescript,
  SiPostgresql,
  SiTailwindcss,
  SiSpringboot,
  SiPandas,
  SiFlutter,
  SiFigma,
  SiRuby,
  SiRubyonrails,
  SiC,
} from "react-icons/si";

export const skillsMap = [
  { name: "React", icon: FaReact },
  { name: "Node.js", icon: FaNodeJs },
  { name: "JavaScript", icon: SiJavascript },
  { name: "Python", icon: FaPython },
  { name: "Docker", icon: FaDocker },
  { name: "AWS", icon: FaAws },
  { name: "Flask", icon: FaFlask },
  { name: "SQL", icon: FaDatabase },
  { name: "Ruby", icon: SiRuby },
  { name: "Git", icon: FaGitAlt },
  { name: "GitHub", icon: FaGithub },
  { name: "Rails", icon: SiRubyonrails },
  { name: "HTML", icon: FaHtml5 },
  { name: "CSS", icon: FaCss3Alt },
  { name: "TypeScript", icon: SiTypescript },
  { name: "PostgreSQL", icon: SiPostgresql },
  { name: "Tailwind", icon: SiTailwindcss },
  { name: "Java", icon: FaJava },
  { name: "Spring Boot", icon: SiSpringboot },
  { name: "Swift", icon: FaSwift },
  { name: "Objective-C", icon: SiC },
  { name: "Pandas", icon: SiPandas },
  { name: "Flutter", icon: SiFlutter },
  { name: "Figma", icon: SiFigma },
  { name: "C", icon: SiC },
];
